project:
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false

website:
  title: "LANDFIRE-Powered Landscape Assessment"
  navbar:
    search: TRUE
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: current.qmd
        text: Current
      - href: late.qmd
        text: Late Succession
      - href: fire.qmd
        text: Wildfire Exposure
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: source

